# Staging Database Configuration
doctrine:
    dbal:
        default_connection: admin
        connections:
            admin:
                driver:   %database_driver%
                host:     %database_host%
                dbname:   ninethousand_stage
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
