# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_home:
    resource: "@NineThousandNineThousandBundle/Resources/config/routing.xml"
    prefix:   /

ninethousand_jobqueue:
    resource: "@NineThousandJobqueueBundle/Resources/config/routing.xml"
    prefix:   /jobqueue
