#!/usr/bin/env php
<?php

umask(0002);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();

// Enforce ZF APPLICATION_ENV convention
if (! defined('APPLICATION_ENV')) {;
    // If on production machine, hostname will contain "collegedegrees.com"
    $default = strpos('.collegedegrees.com', php_uname('h'))
             ? 'production'
             : 'development';

    // Use existing APPLICATION_ENV or default
    define('APPLICATION_ENV', getenv('APPLICATION_ENV') ?: $default);
}

// Convert application environment to Symfony-friendly version
if (!$env = $input->getParameterOption(array('--env', '-e'))) {
    $env = (APPLICATION_ENV === 'staging'     ? 'stage'
         : (APPLICATION_ENV === 'testing'     ? 'test'
         : (APPLICATION_ENV === 'development' ? 'dev'
         : 'prod')));
}

$debug = !$input->hasParameterOption(array('--no-debug', ''));

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run();
