<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110811143959 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE jobqueue_job_arg");
        $this->addSql("DROP TABLE jobqueue_job_param");
        $this->addSql("ALTER TABLE jobqueue_param ADD job_id INT DEFAULT NULL, DROP job");
        $this->addSql("ALTER TABLE jobqueue_param ADD FOREIGN KEY (job_id) REFERENCES jobqueue_job(id)");
        $this->addSql("CREATE INDEX IDX_F9BD1B8DBE04EA9 ON jobqueue_param (job_id)");
        $this->addSql("ALTER TABLE jobqueue_arg ADD job_id INT DEFAULT NULL, DROP job");
        $this->addSql("ALTER TABLE jobqueue_arg ADD FOREIGN KEY (job_id) REFERENCES jobqueue_job(id)");
        $this->addSql("CREATE INDEX IDX_6BF1EAB6BE04EA9 ON jobqueue_arg (job_id)");
        $this->addSql("ALTER TABLE jobqueue_tag DROP job");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE jobqueue_job_arg (job_id INT NOT NULL, arg_id INT NOT NULL, UNIQUE INDEX UNIQ_BE468A3CE891D6B (arg_id), INDEX IDX_BE468A3BE04EA9 (job_id), PRIMARY KEY(job_id, arg_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE jobqueue_job_param (job_id INT NOT NULL, param_id INT NOT NULL, UNIQUE INDEX UNIQ_CDBE7F805647C863 (param_id), INDEX IDX_CDBE7F80BE04EA9 (job_id), PRIMARY KEY(job_id, param_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE jobqueue_job_arg ADD CONSTRAINT jobqueue_job_arg_ibfk_1 FOREIGN KEY (job_id) REFERENCES jobqueue_job(id)");
        $this->addSql("ALTER TABLE jobqueue_job_arg ADD CONSTRAINT jobqueue_job_arg_ibfk_2 FOREIGN KEY (arg_id) REFERENCES jobqueue_arg(id)");
        $this->addSql("ALTER TABLE jobqueue_job_param ADD CONSTRAINT jobqueue_job_param_ibfk_1 FOREIGN KEY (job_id) REFERENCES jobqueue_job(id)");
        $this->addSql("ALTER TABLE jobqueue_job_param ADD CONSTRAINT jobqueue_job_param_ibfk_2 FOREIGN KEY (param_id) REFERENCES jobqueue_param(id)");
        $this->addSql("ALTER TABLE jobqueue_arg DROP FOREIGN KEY ");
        $this->addSql("DROP INDEX IDX_6BF1EAB6BE04EA9 ON jobqueue_arg");
        $this->addSql("ALTER TABLE jobqueue_arg ADD job INT NOT NULL, DROP job_id");
        $this->addSql("ALTER TABLE jobqueue_param DROP FOREIGN KEY ");
        $this->addSql("DROP INDEX IDX_F9BD1B8DBE04EA9 ON jobqueue_param");
        $this->addSql("ALTER TABLE jobqueue_param ADD job INT NOT NULL, DROP job_id");
        $this->addSql("ALTER TABLE jobqueue_tag ADD job INT NOT NULL");
    }
}
