#Projects data
projects:
  - title               : "Jobqueue"
    slug                : "jobqueue"
    description         : "A Simple, extensible, job queue component."
    home_path           : "ninethousand/ninethousand-jobqueue"
    documentation_url   : "http://dev.ninethousand.org/project/jobqueue/ninethousand/ninethousand-jobqueue/blob/master/README.md"
    github_url          : "https://github.com/ninethousand/ninethousand-jobqueue"
    issues_url          : "http://dev.ninethousand.org/project/jobqueue/ninethousand/ninethousand-jobqueue/issues"
  - title               : "Phingistrano"
    slug                : "phingistrano"
    description         : "Building and deploying projects based on Phing."
    home_path           : "CodeMeme/Phingistrano"
    documentation_url   : "http://dev.ninethousand.org/project/phingistrano/CodeMeme/Phingistrano/blob/master/README.md"
    github_url          : "https://github.com/CodeMeme/Phingistrano"
    issues_url          : "http://dev.ninethousand.org/project/phingistrano/CodeMeme/Phingistrano/issues"
  - title               : "Compredux"
    slug                : "compredux"
    home_path           : "ninethousand/ninethousand-compredux"
    description         : "A content filtering web proxy."
    documentation_url   : "http://dev.ninethousand.org/project/compredux/ninethousand/ninethousand-compredux/blob/master/README.md"
    github_url          : "https://github.com/ninethousand/ninethousand-compredux"
    issues_url          : "http://dev.ninethousand.org/project/compredux/ninethousand/ninethousand-compredux/issues"
