#Projects data
projects:
  - title               : "Jobqueue"
    slug                : "jobqueue"
    description         : "A Simple, extensible, job queue component."
    documentation_url   : "https://github.com/ninethousand/ninethousand.org/blob/master/README.md"
    github_url          : "https://github.com/ninethousand/ninethousand-jobqueue"
    issues_url          : "https://github.com/ninethousand/ninethousand-jobqueue/issues"
  - title               : "Phingistrano"
    slug                : "phingistrano"
    description         : "Building and deploying projects based on Phing."
    documentation_url   : "https://github.com/CodeMeme/Phingistrano/blob/master/README.md"
    github_url          : "https://github.com/CodeMeme/Phingistrano"
    issues_url          : "https://github.com/CodeMeme/Phingistrano/issues"
  - title               : "Community Wares"
    slug                : "community"
    description         : "Libraries for community based applications."
    documentation_url   : "#"
    github_url          : "#"
    issues_url          : "#"